pre-push: format lint build

lint:
	pnpm lint

format:
	pnpm format

build:
	pnpm build


auto-push-main:
	git add .
	git commit -m "auto-commit"
	git push origin main

auto-push:
	git add .
	git commit -m "auto-commit"
	git push origin HEAD
