# Generated by Django 4.0.4 on 2022-10-29 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=100, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(default='materials/NontalonLogo.png', upload_to='uploads/%Y/%m/%d/')),
                ('caption', models.CharField(default='', max_length=120, verbose_name='Caption')),
                ('author', models.CharField(default='anonymous', max_length=255)),
                ('description', models.TextField()),
                ('body', models.TextField(default='')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Article?')),
                ('is_picked_up', models.BooleanField(default=False, verbose_name='Picked up Article?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
    ]
